services:
  # Query parameter converter
  request.paramconverter.querystring:
    class:  Yay\Component\HttpFoundation\Request\ParamConverter\QueryStringConverter
    tags:
      - { name: request.param_converter, priority: -2, converter: QueryString }
  # Header field converter
  request.paramconverter.headerfield:
    class:  Yay\Component\HttpFoundation\Request\ParamConverter\HeaderFieldConverter
    tags:
      - { name: request.param_converter, priority: -2, converter: HeaderField }
  # Header field converter
  request.paramconverter.jsonfield:
    class:  Yay\Component\HttpFoundation\Request\ParamConverter\JsonFieldConverter
    tags:
      - { name: request.param_converter, priority: -2, converter: JsonField }

  # Serializer extensions
  yay.serializer.handler.links:
    class:  Yay\Bundle\ApiBundle\Serializer\EventListener\LinkListener
    arguments:
      - '@router'
    tags:
      - { name: jms_serializer.event_listener, event: serializer.post_serialize, method: onPostSerialize, direction: serialization }

  # Test Achievement Validator
  yay.achievement_validation.validator.test_achievement:
    class:  '%yay.achievement_validation.validator.expression_language.class%'
    arguments:
      - >
        achievement.getName() in ['yay.achievement.test_achievement'] and
        filteredPersonalActions.count() >= 5
    tags:
        - { name: yay.achievement_validator }
