imports:
    - { resource: services_dev.yml }

services:
    yay.achievement.test_achievement:
        class: Yay\Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
        arguments:
            - >
                achievement.getName() in ['yay.achievement.test_achievement'] and
                actions.count() >= 5
        tags:
            - { name: yay.achievement_validator }