services:
    _defaults:
        autoconfigure: true
    demo-achievement-validator-01:
        class: Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
        arguments:
            - 'achievement.getName() in [''demo-achievement-01''] and actions.count() >= 5'
        tags:
            - yay.achievement_validator
    demo-achievement-validator-02:
        class: Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
        arguments:
            - 'achievement.getName() in [''demo-achievement-02''] and actions.count() >= 10'
        tags:
            - yay.achievement_validator
    demo-chain:
        class: Component\Webhook\Incoming\Processor\ChainProcessor
        arguments:
            - demo-chain
            -
                - demo-thirdparty-action
                - demo-thirdparty-user
        tags:
            - yay.webhook_incoming.processor
    demo-thirdparty-action:
        class: \Yay\Component\Webhook\Incoming\DummyProcessor
        arguments:
            - demo-thirdparty-action
            -
                third_party.action: demo.action
        tags:
            - yay.webhook_incoming.processor
    demo-thirdparty-user:
        class: \Yay\Component\Webhook\Incoming\DummyProcessor
        arguments:
            - demo-thirdparty-user
            -
                third_party.user: jane.doe
        tags:
            - yay.webhook_incoming.processor
