dist: trusty
language: generic
sudo: false

git:
    depth: 1

services:
    - docker

before_script:
    - sed -i -e 's/data:cached/data/g' docker-compose.yml && cat docker-compose.yml
    - >
        echo "RUN apk add --no-cache --virtual .build-deps autoconf gcc make g++ zlib-dev file g++ libc-dev make pkgconf && \\
            wget http://xdebug.org/files/xdebug-2.5.5.tgz && \\
            tar -zxvf xdebug-2.5.5.tgz && \\
            cd xdebug-2.5.5 && phpize && \\
            ./configure --enable-xdebug && make && make install && \\
            echo \"zend_extension=xdebug.so\" > \$PHP_INI_DIR/conf.d/xdebug.ini && \\
            apk del .build-deps && rm -rf tmp/*" >> DOCKERFILE && cat DOCKERFILE
    - make install

script: make test-coverage
