dist: trusty
language: generic
sudo: required

addons:
    apt:
        packages:
            - pv

git:
    depth: 1

services:
    - docker

before_script:
    - sed -i -e 's/data:cached/data/g' docker-compose.yml
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";

jobs:
  include:
    - stage: "Test"
      before_script:
      - make install 2>&1 "$TRAVIS_BUILD_DIR"/install.log | pv > /dev/null -t
      script: make test-coverage
      after_success:
      - bash <(curl -s https://codecov.io/bash)
      - cat "$TRAVIS_BUILD_DIR"/install.log
    - stage: "Build Image: yay-api:stable"
      after_success:
      - if [ "$TRAVIS_BRANCH" == "master" ]; then DOCKER_ENV=stable make default-publish; fi
    - stage: "Build Docker Image: yay-api:dev"
      after_success:
      - if [ "$TRAVIS_BRANCH" != "master" ]; then DOCKER_ENV=dev make default-publish; fi
    - stage: "Build Docker Image: yay-api-demo:stable"
      after_success:
      - if [ "$TRAVIS_BRANCH" == "master" ]; then DOCKER_ENV=stable make demo-publish; fi
    - stage: "Build Docker Image: yay-api-demo:dev"
      after_success:
      - if [ "$TRAVIS_BRANCH" != "master" ]; then DOCKER_ENV=dev make demo-publish; fi

