dist: trusty
language: php
sudo: false

php:
    - 7.0
    - 7.1
    - 7.2-rc
    - nightly
    - hhvm

git:
    depth: 1

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache: composer

services:
    - docker

notifications:
  email:
    recipients:
      - one@example.com
    on_success: never
    on_failure: always

before_script:
    - composer install --no-interaction

script: make
