dist: trusty
language: php
sudo: false

php:
    - 7.1
    - 7.2
    - hhvm

git:
    depth: 1

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache: composer

services:
    - docker

before_script:
    - composer install --no-interaction

script: make test
