dist: trusty
language: generic
sudo: required

addons:
    apt:
        packages:
            - pv

git:
    depth: 1

services:
    - docker

jobs:
  include:
    - stage: "Test"
      before_script:
      - sed -i -e 's/data:cached/data/g' docker-compose.yml
      - make install 2>&1 "$TRAVIS_BUILD_DIR"/install.log | pv > /dev/null -t
      script:
      - make test-coverage
      after_success:
      - bash <(curl -s https://codecov.io/bash)
      - cat "$TRAVIS_BUILD_DIR"/install.log
    - stage: "Build Image: yay-api:stable"
      if: branch = master AND type IN (push) AND fork = false
      before_script:
      - sed -i -e 's/data:cached/data/g' docker-compose.yml
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      script:
      - DOCKER_ENV=stable make default-publish
    - stage: "Build Docker Image: yay-api:dev"
      if: branch != master AND type IN (push) AND fork = false
      before_script:
      - sed -i -e 's/data:cached/data/g' docker-compose.yml
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      script:
      - DOCKER_ENV=dev make default-publish
    - stage: "Build Docker Image: yay-demo:stable"
      if: branch = master AND type IN (push) AND fork = false
      before_script:
      - sed -i -e 's/data:cached/data/g' docker-compose.yml
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      script:
      - DOCKER_ENV=stable make demo-publish
    - stage: "Build Docker Image: yay-demo:dev"
      if: branch != master AND type IN (push) AND fork = false
      before_script:
      - sed -i -e 's/data:cached/data/g' docker-compose.yml
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
      script:
      - DOCKER_ENV=dev make demo-publish

