# Web Server
web:
    build: ./
    ports:
        - "50080:80"
    links:
        - mysqldb
        - redis
        - blackfire
        - mail
    volumes:
        - ./:/data:cached
    env_file:
        - .docker.env
        - .docker.local.env

# Command Line Tools
cli:
    build: ./
    links:
        - mysqldb
        - redis
        - mail
    volumes:
        - ./:/data:cached
    env_file:
        - .docker.env
        - .docker.local.env

# MySQL
mysqldb:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dev
    ports:
        - "53306:3306"
# Redis
redis:
    image: redis:latest
    ports:
        - "56379:6379"

# Profiler
blackfire:
    image: blackfire/blackfire
    ports:
        - "8707:8707"
    env_file:
        - .docker.env
        - .docker.local.env

# Mail
mail:
    image: schickling/mailcatcher
    ports:
        - "50081:1080"
