# Web Server
web:
    build: ./
    ports:
        - "50080:80"
    links:
        - mysqldb
        - redis
        - blackfire
        - mail
    volumes:
        - ./:/data:cached
    environment:
        APP_MODE: web
        APP_ENV: dev
        APP_DEBUG: 1
        DATABASE_HOST: mysqldb
        DATABASE_NAME: dev
        DATABASE_USER: root
        DATABASE_PASSWORD: root
        REDIS_HOST: redis
        REDIS_PORT: 6379
        MAILER_URL: smtp://mail:1025

# Command Line Tools
cli:
    build: ./
    links:
        - mysqldb
        - redis
        - mail
    volumes:
        - ./:/data:cached
    environment:
        APP_MODE: web
        APP_ENV: dev
        APP_DEBUG: 1
        DATABASE_HOST: mysqldb
        DATABASE_NAME: dev
        DATABASE_USER: root
        DATABASE_PASSWORD: root
        REDIS_HOST: redis
        REDIS_PORT: 6379
        MAILER_URL: smtp://mail:1025

# MySQL
mysqldb:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: dev
    ports:
        - "53306:3306"
# Redis
redis:
    image: redis:latest
    ports:
        - "56379:6379"

# Profiler
blackfire:
    image: blackfire/blackfire
    environment:
        - BLACKFIRE_SERVER_ID
        - BLACKFIRE_SERVER_TOKEN
    ports:
        - "8707:8707"

# Mail
mail:
    image: schickling/mailcatcher
    ports:
        - "50081:1080"