Component\Entity\Achievement\ActionDefinition:
  properties:
    name:
      groups:
        - 'action.index'
        - 'action.show'
        - 'achievement.index'
        - 'achievement.show'
    label:
      groups:
        - 'action.index'
        - 'action.show'
        - 'achievement.index'
        - 'achievement.show'
    description:
      groups:
        - 'action.show'
        - 'achievement.show'


