Component\Entity\Achievement\PersonalAchievement:
  exclusion_policy: ALL
  properties:
    achievedAt:
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
  virtual_properties:
    name:
      exp: 'object.getAchievementDefinition().getName()'
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
    label:
      exp: 'object.getAchievementDefinition().getLabel()'
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
    description:
      exp: 'object.getAchievementDefinition().getDescription()'
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
    points:
      exp: 'object.getAchievementDefinition().getPoints()'
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
    imageUrl:
        exp: 'object.getAchievementDefinition().getImageUrl()'
        groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
