Component\Entity\Player:
  exclusion_policy: ALL
  accessor_order: custom
  custom_accessor_order: [name, username, ...]
  properties:
    name:
      groups:
        - 'player.index'
        - 'player.show'
        - 'leaderboard.index'
        - 'player.create'
    username:
      groups:
        - 'player.index'
        - 'player.show'
        - 'leaderboard.index'
        - 'player.create'
    createdAt:
      groups:
        - 'player.index'
        - 'player.show'
        - 'leaderboard.index'
        - 'player.create'
    score:
      groups:
        - 'player.show'
        - 'leaderboard.index'
        - 'player.index'
    email:
      groups:
        - 'player.create'
    imageUrl:
      groups:
        - 'player.show'
        - 'leaderboard.index'
        - 'player.index'
        - 'player.create'