services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yay\Bundle\IntegrationBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Yay\Bundle\IntegrationBundle\Service\InstallerService:
        public: true

    Symfony\Component\Config\Definition\Processor: ~
    Yay\Bundle\IntegrationBundle\Configuration\Configuration: ~
    Yay\Bundle\IntegrationBundle\Configuration\ConfigurationTransformer: ~
