# JMS Serializer
jms_serializer:
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        directories:
            yay:
                namespace_prefix: 'Component\Entity'
                path: "@Api/Resources/config/serializer"
    property_naming:
        enable_cache: true
    visitors:
            json:
                options: 192
