Yay\Component\Entity\Achievement\AchievementDefinition:
  type: entity
  table: achievement_definition
  # Primary Key
  id:
    name:
      type: string
  # Columns
  fields:
    createdAt:
      type: datetime
    label:
      type: string
    description:
      type: string
    points:
      type: integer
  # Relationships
  oneToMany:
    personalAchievements:
      targetEntity: 'Yay\Component\Entity\Achievement\PersonalAchievement'
      mappedBy: achievementDefinition
      cascade: [ 'persist', 'refresh' ]
  manyToMany:
    actionDefinitions:
      targetEntity: 'Yay\Component\Entity\Achievement\ActionDefinition'
      cascade: [ 'persist', 'refresh' ]
      joinTable:
        name: achievement_action_definition
        joinColumns:
          achievement_definition:
            referencedColumnName: name
        inverseJoinColumns:
          action_definition:
            referencedColumnName: name
