Yay\Component\Entity\Achievement\ActionDefinition:
  type: entity
  table: action_definition
  # Primary Key
  id:
    name:
      type: string
  # Columns
  fields: ~
  # Relationships
  oneToMany:
    personalActions:
      targetEntity: 'Yay\Component\Entity\Achievement\PersonalAction'
      mappedBy: actionDefinition
