Yay\Component\Entity\Achievement\Step:
  type: entity
  table: step
  # Primary Key
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  # Columns
  fields:
    achievedAt:
      type: datetime
  # Relationships
  manyToOne:
    actionDefinition:
      targetEntity: 'Yay\Component\Entity\Achievement\ActionDefinition'
      inversedBy: steps
      joinColumn:
        name: action_definition
        referencedColumnName: name
    player:
      targetEntity: 'Yay\Component\Entity\Player'
      inversedBy: steps
      joinColumn:
        name: player_id
        referencedColumnName: id
