FROM ubuntu:16.04

ENV COMPOSER_DISABLE_XDEBUG_WARN 1
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN PACKAGES="\
        build-essential \
        curl \
        php-cli \
        php-mysql \
        php-intl \
        php-xml \
        php-curl \
        php-dom \
        wget \
        zip \
        unzip \
        git \
        libfreetype6 \
        libfontconfig \
        ranger \
        nano \
        redis-tools \
    " && \
    apt-get update && \
    apt-get install -y $PACKAGES && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN PACKAGES="\
        nodejs \
    " && \
    apt-get update && \
    apt-get remove --purge -y $PACKAGES  && \
    curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get install -y $PACKAGES && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN PACKAGES="\
        yarn \
    " && \
    npm install -g $PACKAGES

#RUN ( \
#    echo "opcache.memory_consumption=256"; \
#    echo "opcache.interned_strings_buffer=8"; \
#    echo "opcache.max_accelerated_files=30000"; \
#    echo "opcache.revalidate_freq=5"; \
#    echo "opcache.fast_shutdown=1"; \
#    echo "opcache.enable_cli=1"; \
#    ) > /etc/php/7.0/cli/conf.d/99-opcache.ini

RUN cd /tmp && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    rm -rf /tmp/*

RUN cd /tmp && \
    curl -LsS https://get.symfony.com/installer -o /usr/local/bin/symfony && \
    chmod a+x /usr/local/bin/symfony && \
    rm -rf /tmp/*
