FROM ubuntu:16.04

RUN PACKAGES="\
        php-cli \
        php-mysql \
        php-intl \
        php-xml \
        php-curl \
        php-dom \
        php-mbstring \
        php-apcu \
    " && \
    apt-get update && \
    apt-get install -y $PACKAGES && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#RUN ( \
#    echo "opcache.memory_consumption=256"; \
#    echo "opcache.interned_strings_buffer=8"; \
#    echo "opcache.max_accelerated_files=30000"; \
#    echo "opcache.revalidate_freq=5"; \
#    echo "opcache.fast_shutdown=1"; \
#    echo "opcache.enable_cli=1"; \
#    ) > /etc/php/7.0/cli/conf.d/99-opcache.ini
