parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Engine\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Component\Engine\Engine: { public: true }
    Component\Engine\Storage\DoctrineStorage: ["@=service('doctrine').getManager()"]
    Component\Engine\StorageInterface: '@Component\Engine\Storage\DoctrineStorage'
    Component\Engine\AchievementValidatorCollection: ~ 
    Component\Engine\EventListener\ActivityListener:
        tags:
            - { name: yay.event_listener, event: yay.engine.grant_personal_action, method: onGrantPersonalAction }
            - { name: yay.event_listener, event: yay.engine.grant_personal_achievement, method: onGrantPersonalAchievement }
            - { name: yay.event_listener, event: yay.engine.create_player, method: onCreatePlayer }
