parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Engine\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Component\Engine\Engine: { public: true }
    Component\Engine\Storage\DoctrineStorage: ["@=service('doctrine').getManager()"]
    Component\Engine\Storage\StorageInterface: '@Component\Engine\Storage\DoctrineStorage'
    Component\Engine\AchievementValidatorCollection: ~ 
    Component\Engine\EventListener\ActivityListener:
        tags:
            - { name: yay.event_listener, 
                event: !php/const Component\Engine\Events::GRANT_PERSONAL_ACTION, 
                method: onGrantPersonalAction }
            - { name: yay.event_listener, 
                event: !php/const Component\Engine\Events::GRANT_PERSONAL_ACHIEVEMENT, 
                method: onGrantPersonalAchievement }
            - { name: yay.event_listener, 
                event: !php/const Component\Engine\Events::CREATE_PLAYER, 
                method: onCreatePlayer }
            - { name: yay.event_listener, 
                event: !php/const Component\Engine\Events::CHANGE_LEVEL, 
                method: onLevelChanged }
            - { name: yay.event_listener, 
                event: !php/const Component\Engine\Events::CHANGE_SCORE, 
                method: onScoreChanged }