
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Mail\Service\Mailer:
        arguments: [ '@templating', '@mailer' ]

    App\Mail\EventListener\MailListener:
        tags:
            - { name: yay.event_listener, event: yay.engine.grant_personal_action, method: onGrantPersonalAction }
            - { name: yay.event_listener, event: yay.engine.grant_personal_achievement, method: onGrantPersonalAchievement }
            - { name: yay.event_listener, event: yay.engine.create_player, method: onCreatePlayer }
