ApiBundle:
    resource: "@Api/Resources/config/routing.yml"
    prefix:   /api

IntegrationBundle:
    resource: "@Integration/Resources/config/routing.yml"
    prefix:   /integration

WebhookBundle:
    resource: "@Webhook/Resources/config/routing.yml"
    prefix:   /webhook

#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc

AppCompatNelmioApiDocBundle:
    resource: "@Compat/Resources/config/NelmioApiDocBundle/routing.yml"
    prefix:   /api/doc
