Component\Entity\Activity:
  type: entity
  table: activity
  # Primary Key
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  # Columns
  fields:
    createdAt:
      type: datetime
    name:
      type: string
    data:
      type: json
  # Relationships
  manyToOne:
    player:
      targetEntity: 'Component\Entity\Player'
      inversedBy: activities
      cascade: [ 'persist', 'refresh' ]
      joinColumn:
        name: player_id
        referencedColumnName: id
        cascade: [ 'persist', 'refresh' ]