services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yay\Bundle\WebhookBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Yay\Component\Webhook\Webhook: ~
    Yay\Component\Webhook\Incoming\ProcessorCollection: ~
    Yay\Component\Webhook\Outgoing\ProcessorCollection: ~

    yay.webhook.incoming_processor.test-processor-01:
        class: Yay\Component\Webhook\Incoming\Processor\ChainProcessor
        arguments:
            - test-processor-01
            -
                - '@yay.webhook.incoming_processor.test-processor-02'
                - '@yay.webhook.incoming_processor.test-processor-03'

    yay.webhook.incoming_processor.test-processor-02:
        class: Yay\Component\Webhook\Incoming\Processor\DummyProcessor
        arguments:
            - test-processor-02
            -
                player: jane.doe,
                actions: [test-action]

    yay.webhook.incoming_processor.test-processor-03:
        class: Yay\Component\Webhook\Incoming\Processor\NullProcessor
        arguments:
            - test-processor-03
