parameters: ~

services:
  # Demo Achievement Validators
  yay.achievement_validation.validator.demo_achievement_1:
    class:  '%yay.achievement_validation.validator.expression_language.class%'
    arguments:
      - >
        achievement.getName() in ['yay.achievement.demo_achievement_1'] and
        filteredPersonalActions.count() >= 5
    tags:
        - { name: yay.achievement_validator }
  yay.achievement_validation.validator.demo_achievement_2:
    class:  '%yay.achievement_validation.validator.expression_language.class%'
    arguments:
      - >
        achievement.getName() in ['yay.achievement.demo_achievement_2'] and
        filteredPersonalActions.count() >= 10
    tags:
        - { name: yay.achievement_validator }
