Yay\Component\Entity\Achievement\PersonalAchievement:
  exclusion_policy: ALL
  properties:
    achievedAt:
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
  virtual_properties:
    name:
      exp: object.getAchievementDefinition().getName()
      groups:
        - 'player.show'
        - 'player.personal_achievements.show'
        - 'progress.submit'
