Yay\Component\Entity\Achievement\PersonalAction:
  exclusion_policy: ALL
  properties:
    achievedAt:
      groups:
        - 'player.personal_actions.show'
  virtual_properties:
    name:
      exp: object.getActionDefinition().getName()
      groups:
        - 'player.personal_actions.show'

