parameters: ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Yay\Bundle\EngineBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Yay\Component\Engine\Engine: { public: true }
    Yay\Component\Engine\Storage\DoctrineStorage: ["@=service('doctrine').getManager()"]
    Yay\Component\Engine\StorageInterface: '@Yay\Component\Engine\Storage\DoctrineStorage'
    Yay\Component\Engine\AchievementValidatorCollection: ~ #[!tagged yay.achievement_validator]
