parameters:
  # Core Engine
  yay.engine.engine.class: Yay\Component\Engine\Engine
  # Core Engine
  yay.engine.storage.class: Yay\Component\Engine\Storage\DoctrineStorage
  # Core Validation
  yay.achievement_validation.validator_collection.class: Yay\Component\Engine\AchievementValidatorCollection
  # Core Validation - Validator
  yay.achievement_validation.validator.expression_language.class: Yay\Component\Engine\AchievementValidator\Validator\ExpressionLanguageValidator
  # Core Validation - Filter
  yay.achievement_validation.filter.unique_achievement.class: Yay\Component\Engine\AchievementValidator\Filter\UniqueAchievementFilter
  yay.achievement_validation.filter.only_new_achievement.class: Yay\Component\Engine\AchievementValidator\Filter\OnlyNewAchievementFilter

services:
  # Core Engine incl. Storage
  yay.engine:
    class:  '%yay.engine.engine.class%'
    arguments:
      - '@yay.engine.storage'
      - '@yay.achievement_validation.validator_collection'

  yay.engine.storage:
    class:  '%yay.engine.storage.class%'
    arguments:
      - "@=service('doctrine').getManager()"

  # Core Validation
  yay.achievement_validation.validator_collection:
    class:  '%yay.achievement_validation.validator_collection.class%'

  yay.achievement_validation.filter.unique:
    class:  '%yay.achievement_validation.validator_collection.class%'

